### ISSUE TITLE
Nasměrovat pod doménu https://amcr-help.aiscr.cz/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr-help#1]
@petrpajdla prosím domluv se s @MichalKminek, aby to neviselo na té výchozí doméně od GitHub. Koukal jsem do nastavení a možné to je (viz https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site)

**Comment by petrpajdla** [comment]
Jasně, jde to, jen jsem s tím chtěl počkat, až to bude kompletnější, každopádně to vedu v evidenci.

**Comment by petrpajdla** [comment]
@motyc máš nějakou představu, kde by to mělo viset? Předpokládám subdoménu aiscr.cz?

Varianty, co mně napadají:

- docs.aiscr.cz
- help.aiscr.cz
- man.aiscr.cz
- resources.aiscr.cz

**Comment by petrpajdla** [comment]
Aaah ok už to vidím v názvu issue https://amcr-help.aiscr.cz/, necháme tedy tohle?

**Comment by motyc** [comment]
@petrpajdla Jop, myslel jsem tuhle, ale nechám se klidně přesvědčit. Jen mi přišlo fajn to držet v kombinaci s tou AMČR, protože to zase nebude manuál ke všem nástrojům...

**Comment by petrpajdla** [comment]
Jop, to amcr-help mi zní ok. Přemýšlel jsem, jestli nedat něco jako docs, když je to taková obecnější dokumentace, ale ta help je asi tak nejobecnější co se tam tak dá dát...

@MichalKminek Michale mohl byste prosím prozkoumat, jak to přesně provést? Tady je návod od GH: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by petrpajdla** [comment]
Uzavřeno v 1e1b6625e81d55a555cc9fd874b698f1d4a9091d

- [ ] Pohlídat, jestli se dalším spuštěním akce nesmaže file CNAME v gh-pages.

**Comment by motyc** [comment]
Tak vyřešeno, zavírám.

**Comment by petrpajdla** [comment]
Myslím, že to CNAME se bude muset vytvářet někde v tom automatickém buildu, budu to ještě sledovat.

**Comment by petrpajdla** [comment]
Zde řešení, není třeba vytvářet soubor akcí, ale jde přidat mezi resources: https://github.com/quarto-dev/quarto-cli/discussions/3249

**Comment by motyc** [comment]
@petrpajdla Já myslím, že už s tím není třeba nic dělat. Po tom, co jsem to přidal přímo do main, tak se to správně zaregistrovalo a udělalo to samo i nějaké změny v kódu v gh-pages branchi. Takže myslím, že to opravdu může zůstat a funguje to.

**Comment by petrpajdla** [comment]
Aha zajímavé, tak možná to GitHub dělá sám, že CNAME automaticky propíše z main do gh-pages, když ho detekuje, protože jinak se podle mně obsah gh-pages komplet smaže při každém novém buildu.

Každopádně to správné řešení je mít ten soubor uvedený v "resources", pak ho z main kopíruje do gh-pages už quarto při renderu stránek. Stejně to budu dělat i pro soubory, které budeme mít "ke stažení", tak zkusím tenhle postup a uvidíme.
