### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by petrpajdla** [ARUP-CAS/aiscr-webamcr-help#12]
@motyc Budeme chtít sledovat traffic pomocí Google Analyticks nebo něco takového? Budu asi potřebovat vygenerovat nějaký token nebo jak se to dělalo prosím.

**Comment by petrpajdla** [comment]
Návod tu: [https://quarto.org/docs/websites/website-tools.html#google-analytics](https://quarto.org/docs/websites/website-tools.html#google-analytics).

**Comment by petrpajdla** [comment]
V tom návodu píší ještě něco o cookie consent, to budeme řešit, nebo nesledujeme provoz na takové úrovni, abysme potřebovali cookies?

**Comment by motyc** [comment]
@petrpajdla Pokud to dokážeš nastavit, bylo by to fajn. Ale tohle bychom potřebovali vyřešit pro celý AIS CR... Bohužel to nemáme nikde a měli bychom. Pokud bychom cookies nepoužívali, můžeme jen měřit přístupy, ale ani netušíme, co jsou opakovaná vrácení a co je někdo nový.

**Comment by petrpajdla** [comment]
Tušil jsem že to tak nějak bude a měli bysme to mít všude. Tady to nastavení vypadá relativně triviálně a je dobře popsané, tak to zkusím nastavit a uvidíme.

**Comment by motyc** [comment]
Ok. Jinak značka tam je a funguje v pořádku, takže až dořešíš ty cookies, můžeš zavřít.

**Comment by petrpajdla** [comment]
Tak ten cookie consent tam v základu přidává takovýhle dialog (ten už jsem trochu nastyloval, defaultně byl přes polovinu okna a zase se mi nechce si s tím CSSkem hrát půl dne):

![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr-help/assets/27239643/770c7d5b-24b9-4fc9-baaf-0eaae5f76136)

Je to v angličtině, ale v další verzi Quarta (ta je zatím v pre-release) bude jazyk respektovat nastavený jazyk stránky.
Text je trochu overkill, protože tam člověk souhlasí i s "targeted ads", což je pro nás bezvýznamné, ale zase je to nejjednodušší řešení a ten dialog i ovládání cookie consentu se generuje automaticky tímhle open source nástrojem (asi by byl použitelný i pro naše ostatní weby): https://www.cookieconsent.com/

Co myslíš @motyc , použít tohle, ikdyž je tam uvedený ten souhlas s targeted ads, nebo se na to vykašlat a nastavit, aby se neukládaly cookies? V nápovědě píšou, že pak to bude dělat tohle, což si úplně nejsem jistý, co vše to pro analytiku znamená, ale asi to bude dávat jen ta osekaná data bez unikátních návštěv: 
_User consent for ad and analytics tracking cookies will be withheld. In this mode, Google Analytics will still collect user data without the user identification, but that data is currently not displayed in the Google Analytics reports._

**Comment by motyc** [comment]
Určitě bych ty cookies nevypínal, jen by nám to komplikovalo život.

Jinak generovat to jde i zde, kde si ten text můžeš přímo nastavit: https://www.cookie-lista.cz/

Nebyla by to cesta? Koukám ale, že jsou různé volby i v tom nástroji, co linkuješ Ty, to nejde nastavit přesněji? Ty cílené reklamy bych tam ideálně nezmiňoval, protože to opravdu nepoužíváme.

**Comment by petrpajdla** [comment]
Quarto defaultně používá ten nástroj co jsem posílal, a tam přímo v nápovědě píšou, že zatím text upravit nejde, protože tam mají vlastní autoritativní překlady (ty se automaticky přepínají podle nastavení stránky/browseru), ale tu možnost úpravy textu chystají, tak je otázka, jestli nezkusit počkat, pořád je to nejjednodušší řešení a out of the box by to řešilo i další jazyky...

Použít nějaké jiné řešení jde taky, jen už je to vždycky složitější tím, že musíme mít nějaké vlastní skripty co budou povolovat ty cookies atd. To co posíláš mi přijde že reálně nic nedělá, to je jen js pro vytvoření té lišty a tlačítka a pak musíš mít ještě skripty, které by zajstily to, že se ty cookies reálně povolí nebo zakážou po kliknutí na to tlačítko...

**Comment by petrpajdla** [comment]
Zatím bych nechal tak a odložil, dořešíme před spouštěním pro veřejnost...

**Comment by motyc** [comment]
Díky za vysvětlení. Souhlas, počkejme.

**Comment by petrpajdla** [comment]
@motyc Jazyk upraven, cookie consent je v češtině, jen neumím hnout s tím, že text a nabídky obsahují i ty targeted ads.

Já bych to neřešil, přijde mi, že poměr cena/výkon za to, že to tam budeme mít není úplně efektivním využitím kapacit - sám bych to neudělal, někdo by musel napsat javascript pro to, aby se ty cookies ukládaly v prohlížeči atd., ikdyby jsme použili nějakou už vygenerovanou lištu...
